#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
CONFIG_FILE=/etc/shadowsocks.json


start() {
    echo "start copy gwflist"
    rm -rf /tmp/lhs_gwflist.conf
    tar xzvf /etc/dnsmasq.d/lhs_gfwlist.conf.tar -C /tmp/
    rm -rf /etc/dnsmasq.d/lhs_gwflist.conf
    ln -s /tmp/lhs_gfwlist.conf /etc/dnsmasq.d/lhs_gwflist.conf
    /etc/init.d/dnsmasq restart
    /etc/init.d/firewall restart
    service_start /data/usr/sbin/ss-redir -c $CONFIG_FILE -b 0.0.0.0
}

stop() {
    service_stop /data/usr/sbin/ss-redir
}
